-- AlterTable
ALTER TABLE "config" ALTER COLUMN "teamBudget" SET DEFAULT 1000,
ALTER COLUMN "teamBudget" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "draft_picks" ALTER COLUMN "costPaid" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "players" ALTER COLUMN "cost" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "teams" ALTER COLUMN "budgetLeft" SET DATA TYPE DOUBLE PRECISION;
